export const UPDATE_DATE_ENTRY_START = "UPDATE_DATE_ENTRY_START";
export const UPDATE_DATE_ENTRY_SUCCESS = "UPDATE_DATE_ENTRY_SUCCESS";
export const UPDATE_DATE_ENTRY_FAILED = "UPDATE_DATE_ENTRY_FAILED";
