export const AUTHENTICATION_START = "AUTHENTICATION_START";
export const SIGNUP_POST_CREDENTIALS_SUCCESS =
  "SIGNUP_POST_CREDENTIALS_SUCCESS";
export const SIGNUP_POST_CREDENTIALS_FAILED = "SIGNUP_POST_CREDENTIALS_FAILED";
export const SIGNIN_POST_CREDENTIALS_SUCCESS =
  "SIGNIN_POST_CREDENTIALS_SUCCESS";
export const SIGNIN_POST_CREDENTIALS_FAILED = "SIGNIN_POST_CREDENTIALS_FAILED";
export const SYNC_LOGOUT = "SYNC_LOGOUT";
export const LOGOUT_MESSAGE = "LOGOUT_MESSAGE";
export const CLEAR_LOGOUT_MESSAGE = "CLEAR_LOGOUT_MESSAGE";
